### ISSUE TITLE
Authorization isn't required for message counts

### ISSUE THREAD

**Issue by joker314** [towerofnix/scratch-notifs#2]
https://api.scratch.mit.edu/users/_nix/messages/count works even if you don't put a ?x-token=${token} on the end.

Awesome project btw!

**Comment by towerofnix** [comment]
I know. See LLK/scratch-rest-api#11.

I should probably change the paragraph text, though.

**Comment by towerofnix** [comment]
(Closing because of 590751a4fe81898b41c8784970421a2e8614061f)

**Comment by joker314** [comment]
Can the token be left blank? If so, you might want to note that. (e.g. "Depending on if Scratch have resolved a bug, you may be able to leave this empty")

**Comment by towerofnix** [comment]
@joker314 On the one hand, maybe; on the other hand, I'm too lazy to make the change to the paragraph text right now. World_Languages has created a program that does exactly the same thing as this but in a prettier, more useful way, and [it's gotten rather popular](https://scratch.mit.edu/projects/203349676/) - 672 love-its and 1202 comments. And of course, that program doesn't have anything about requesting an x-token -- you just stick in a username, and bam, it works.

PS, no, if x-token is set to an invalid value (i.e. a nonexistant token), the page gives you an "Unauthorized" error, even though you don't need to be authenticated to view the page in the first place.
